### PR TITLE
scion-utils control file

### PR DESCRIPTION
**Pull request by worxli**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)

### CODE REVIEW

**Review by klausman — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: all files reviewed, 2 unresolved discussions (waiting on @worxli)

___
*[.gitignore, line 3 at r1](https://reviewable.io/reviews/scionproto/scion-packaging/1#-LJIuqOR13vUEAFqaBVK:-LJIuqOR13vUEAFqaBVL:bf843hd) ([raw file](https://github.com/scionproto/scion-packaging/blob/089a3ade490b7c943053a567bd1936b73f0a8e49/.gitignore#L3)):*
> ```
> *.deb
> */usr/bin/*
> *.gz
> ```

Also add `*.sw?` (vim swapfiles)
___
*[scion-utils/README.md, line 3 at r1](https://reviewable.io/reviews/scionproto/scion-packaging/1#-LJIv0G0BzqWSYz0qyOK:-LJIv0G0BzqWSYz0qyOL:b-nn1vpr) ([raw file](https://github.com/scionproto/scion-packaging/blob/089a3ade490b7c943053a567bd1936b73f0a8e49/scion-utils/README.md#L3)):*
> ```Markdown
> # SCION Utils
> 
> This repo contains the control files to create a `scion-utils` debian package. This includes
> ```

Add `:` at the end.

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: all files reviewed, 2 unresolved discussions (waiting on @klausman)

___
*[.gitignore, line 3 at r1](https://reviewable.io/reviews/scionproto/scion-packaging/1#-LJIuqOR13vUEAFqaBVK:-LJIwMW36lLczT-NDf7l:b-896fix) ([raw file](https://github.com/scionproto/scion-packaging/blob/089a3ade490b7c943053a567bd1936b73f0a8e49/.gitignore#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Also add `*.sw?` (vim swapfiles)
</blockquote></details>

Done.
___
*[scion-utils/README.md, line 3 at r1](https://reviewable.io/reviews/scionproto/scion-packaging/1#-LJIv0G0BzqWSYz0qyOK:-LJIwVbk8on3LWW7zFMC:b-896fix) ([raw file](https://github.com/scionproto/scion-packaging/blob/089a3ade490b7c943053a567bd1936b73f0a8e49/scion-utils/README.md#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Add `:` at the end.
</blockquote></details>

Done.

**Review by klausman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1#-:-LJJ-cTQ-A_R6HryXXBb:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @klausman)

**Review by klausman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by klausman — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by klausman — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by klausman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by klausman — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

___
*[.gitignore, line 3 at r5](https://reviewable.io/reviews/scionproto/scion-packaging/1#-LJYzzv7Cn2yTxfY3Xgo:-LJYzzv7Cn2yTxfY3Xgp:bh1nuqb) ([raw file](https://github.com/scionproto/scion-packaging/blob/cdced0743e5f1bc2675a395161ed383d3637be70/.gitignore#L3)):*
> ```
> *.deb
> */usr/bin/*
> */usr/lib/*
> ```

Collapse this into `*/usr/*` There really shouldn't be a dir of that name anywhere (except for our temp uses, of course)

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1)* status: all files reviewed, 1 unresolved discussion (waiting on @klausman)

___
*[.gitignore, line 3 at r5](https://reviewable.io/reviews/scionproto/scion-packaging/1#-LJYzzv7Cn2yTxfY3Xgo:-LJZ-cBn1xyHtEdQ18j0:b-896fix) ([raw file](https://github.com/scionproto/scion-packaging/blob/cdced0743e5f1bc2675a395161ed383d3637be70/.gitignore#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Collapse this into `*/usr/*` There really shouldn't be a dir of that name anywhere (except for our temp uses, of course)
</blockquote></details>

Done.

**Review by klausman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion-packaging/1#-:-LJZ0K6uB2GaSHdy565X:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @klausman)

**Pull request merged**
